// This file is auto-generated by scripts/models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/moonshotaicn.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../modelcatalog.ts";

export const MOONSHOTAI_CN_MODELS: ChatModelCatalog<typeof values, "moonshotai-cn"> =
	flattenChatModelCatalog("moonshotai-cn", values);

export const MOONSHOTAI_CN_IMAGE_MODELS: ImageModelCatalog<typeof values, "moonshotai-cn"> =
	flattenImageModelCatalog("moonshotai-cn", values);

export const MOONSHOTAI_CN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "moonshotai-cn"> =
	flattenClassifierModelCatalog("moonshotai-cn", values);
